import type { ColumnType } from 'kysely';

/**
 * This file's content is autogenerated by running npm run inspect-db
 * It uses Kysely-codegen tool to inspect your database and generate these types.
 */

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type UserRole = 'admin' | 'user';

export interface Users {
  email: string | null;
  id: Generated<number>;
  password: string;
  role: Generated<UserRole | null>;
  username: string;
  verified: Generated<boolean | null>;
}

export interface DB {
  users: Users;
}
